#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Thu Apr 09 10:23:46 AEST 2026
enableDebugOptions=false
disableUpdateMessage=false
enableShaders=true
maxShadowRenderDistance=0
shaderPack=
