#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Tue Apr 14 13:32:23 AEST 2026
enableDebugOptions=false
disableUpdateMessage=false
enableShaders=true
maxShadowRenderDistance=0
shaderPack=
