# Configuration file

general {
    # Fuel Generator power factor
    D:coefficientFuelGenerator=0.0

    # Nuclear Generator power factor
    D:coefficientNuclearGenerator=0.0

    # Solar Wind Panel power factor
    D:coefficientSolarWindPanel=0.0

    # Gybrid Solar Panel power factor
    D:coefficientSolarPanel=0.0

    # Wind Turbine power factor
    D:coefficientWindTurbine=0.0

    # Rocket Assembly craft speed factor
    D:coefficientSpeedRocketAssembly=1.0
}


